version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - test_db
    environment:
      - NODE_ENV=$NODE_ENV

  db:
    image: postgres:14
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"

  test_db:
    image: postgres:14
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: $TEST_DB_USER
      POSTGRES_PASSWORD: $TEST_DB_PASSWORD
      POSTGRES_DB: $TEST_DB_NAME
    ports:
      - "5433:5432"